# Generated by Django 4.2.10 on 2025-08-08 12:09

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('product.stock_changed', 'Product Stock Changed'), ('order.created', 'Order Created'), ('order.status_changed', 'Order Status Changed'), ('order.cancelled', 'Order Cancelled'), ('order.shipped', 'Order Shipped'), ('order.delivered', 'Order Delivered'), ('payment.created', 'Payment Created'), ('payment.succeeded', 'Payment Succeeded'), ('payment.failed', 'Payment Failed'), ('payment.refunded', 'Payment Refunded'), ('customer.registered', 'Customer Registered'), ('customer.updated', 'Customer Updated'), ('customer.deleted', 'Customer Deleted'), ('inventory.low_stock', 'Low Stock Alert'), ('inventory.out_of_stock', 'Out of Stock'), ('inventory.stock_reserved', 'Stock Reserved'), ('inventory.stock_released', 'Stock Released'), ('notification.sent', 'Notification Sent'), ('notification.failed', 'Notification Failed'), ('notification.delivered', 'Notification Delivered'), ('system.health_check', 'System Health Check'), ('system.error', 'System Error'), ('system.maintenance', 'System Maintenance')], max_length=50)),
                ('source_service', models.CharField(max_length=50)),
                ('target_service', models.CharField(blank=True, max_length=50)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscriber_service', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('source_service', models.CharField(blank=True, max_length=50)),
                ('endpoint_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('api_key', 'API Key')], default='none', max_length=20)),
                ('auth_credentials', models.JSONField(blank=True, default=dict)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_subscriptions',
                'indexes': [models.Index(fields=['subscriber_service'], name='event_subsc_subscri_6c1142_idx'), models.Index(fields=['event_type'], name='event_subsc_event_t_bab99e_idx'), models.Index(fields=['is_active'], name='event_subsc_is_acti_3514c1_idx')],
                'unique_together': {('subscriber_service', 'event_type', 'source_service')},
            },
        ),
        migrations.CreateModel(
            name='EventDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='events.event')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='events.eventsubscription')),
            ],
            options={
                'db_table': 'event_deliveries',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_event_t_c9f56c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source_service'], name='events_source__d0eb41_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['target_service'], name='events_target__cbc320_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_status_8890b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='events_created_9e2206_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['correlation_id'], name='events_correla_d00053_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['scheduled_at'], name='events_schedul_551c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdelivery',
            index=models.Index(fields=['event'], name='event_deliv_event_i_03cb33_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdelivery',
            index=models.Index(fields=['subscription'], name='event_deliv_subscri_20205e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdelivery',
            index=models.Index(fields=['status'], name='event_deliv_status_5baffb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdelivery',
            index=models.Index(fields=['sent_at'], name='event_deliv_sent_at_d41181_idx'),
        ),
    ]
