# Generated by Django 4.2.10 on 2025-08-08 11:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('low_stock_alert', 'Low Stock Alert'), ('price_change', 'Price Change'), ('promotion', 'Promotion'), ('account_verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome'), ('custom', 'Custom')], max_length=30)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_user_id', models.UUIDField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('webhook', 'Webhook'), ('slack', 'Slack'), ('discord', 'Discord')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('sms_provider', models.CharField(blank=True, max_length=50)),
                ('sms_api_key', models.CharField(blank=True, max_length=255)),
                ('sms_api_secret', models.CharField(blank=True, max_length=255)),
                ('sms_from_number', models.CharField(blank=True, max_length=20)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_headers', models.JSONField(blank=True, default=dict)),
                ('webhook_method', models.CharField(blank=True, default='POST', max_length=10)),
                ('rate_limit_per_hour', models.IntegerField(default=100)),
                ('rate_limit_per_day', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_order_updates', models.BooleanField(default=True)),
                ('email_payment_updates', models.BooleanField(default=True)),
                ('email_promotions', models.BooleanField(default=True)),
                ('email_newsletter', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_order_updates', models.BooleanField(default=False)),
                ('sms_payment_updates', models.BooleanField(default=False)),
                ('sms_promotions', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_order_updates', models.BooleanField(default=True)),
                ('push_payment_updates', models.BooleanField(default=True)),
                ('push_promotions', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notificationchannel')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_size', models.PositiveIntegerField(default=100)),
                ('delay_between_batches', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationchannel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationchannel'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.notificationtemplate'),
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('spam', 'Marked as Spam')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notification.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('notification', 'attempt_number')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_a5f01d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_email'], name='notificatio_recipie_be59ab_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_user_id'], name='notificatio_recipie_2db053_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_sent', 'scheduled_at'], name='notificatio_is_sent_feae70_idx'),
        ),
    ]
