# Generated by Django 4.2.10 on 2025-08-08 12:35

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('config_type', models.CharField(choices=[('application', 'Application Config'), ('database', 'Database Config'), ('cache', 'Cache Config'), ('message_queue', 'Message Queue Config'), ('security', 'Security Config'), ('monitoring', 'Monitoring Config'), ('feature_flag', 'Feature Flag')], default='application', max_length=20)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production'), ('testing', 'Testing')], default='production', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('previous_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configurations',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(default='http', max_length=10)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('starting', 'Starting'), ('stopping', 'Stopping'), ('maintenance', 'Maintenance')], default='starting', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('health_check_interval', models.IntegerField(default=30)),
                ('health_check_timeout', models.IntegerField(default=5)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('load_balancer_weight', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_instances',
                'ordering': ['service', 'instance_id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[('api', 'API Service'), ('worker', 'Worker Service'), ('gateway', 'Gateway Service'), ('database', 'Database Service'), ('cache', 'Cache Service'), ('message_queue', 'Message Queue Service'), ('monitoring', 'Monitoring Service'), ('storage', 'Storage Service')], default='api', max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_url', models.URLField()),
                ('health_check_url', models.URLField()),
                ('api_docs_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_secure', models.BooleanField(default=True)),
                ('capabilities', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('service_dependencies', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('config', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Registries',
                'db_table': 'service_registry',
                'ordering': ['service_name'],
                'indexes': [models.Index(fields=['service_name'], name='service_reg_service_aa4099_idx'), models.Index(fields=['service_type'], name='service_reg_service_961878_idx'), models.Index(fields=['status'], name='service_reg_status_cd4fef_idx'), models.Index(fields=['environment'], name='service_reg_environ_cc6767_idx'), models.Index(fields=['last_heartbeat'], name='service_reg_last_he_ea0631_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('disk_usage', models.FloatField(blank=True, null=True)),
                ('network_io', models.FloatField(blank=True, null=True)),
                ('request_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('response_time_avg', models.FloatField(blank=True, null=True)),
                ('response_time_p95', models.FloatField(blank=True, null=True)),
                ('response_time_p99', models.FloatField(blank=True, null=True)),
                ('custom_metrics', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('service_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='service_discovery.serviceinstance')),
            ],
            options={
                'db_table': 'service_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='service_discovery.serviceregistry'),
        ),
        migrations.CreateModel(
            name='ServiceDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('circular', 'Circular')], default='required', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='service_discovery.serviceregistry')),
                ('target_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='service_discovery.serviceregistry')),
            ],
            options={
                'db_table': 'service_dependencies',
                'ordering': ['source_service', 'target_service'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('timeout', 'Timeout'), ('error', 'Error')], max_length=20)),
                ('response_time_ms', models.IntegerField()),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('response_body', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('service_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='service_discovery.serviceinstance')),
            ],
            options={
                'db_table': 'health_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('rollback', 'Rollback')], max_length=20)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by', models.CharField(blank=True, max_length=100)),
                ('change_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='service_discovery.configuration')),
            ],
            options={
                'db_table': 'configuration_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['key'], name='configurati_key_51176b_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['config_type'], name='configurati_config__b82485_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['service_name'], name='configurati_service_874240_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['environment'], name='configurati_environ_8f4c75_idx'),
        ),
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['updated_at'], name='configurati_updated_ecff8a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemetrics',
            index=models.Index(fields=['service_instance'], name='service_met_service_2678d9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemetrics',
            index=models.Index(fields=['recorded_at'], name='service_met_recorde_c18653_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstance',
            index=models.Index(fields=['instance_id'], name='service_ins_instanc_8a35b2_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstance',
            index=models.Index(fields=['service'], name='service_ins_service_45b210_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstance',
            index=models.Index(fields=['status'], name='service_ins_status_02d448_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstance',
            index=models.Index(fields=['last_heartbeat'], name='service_ins_last_he_52a18a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedependency',
            index=models.Index(fields=['source_service'], name='service_dep_source__fc5482_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedependency',
            index=models.Index(fields=['target_service'], name='service_dep_target__f2ced1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedependency',
            index=models.Index(fields=['dependency_type'], name='service_dep_depende_e91327_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicedependency',
            unique_together={('source_service', 'target_service')},
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['service_instance'], name='health_chec_service_d0ece6_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['status'], name='health_chec_status_fc7291_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['checked_at'], name='health_chec_checked_22aed7_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['configuration'], name='configurati_configu_aa44ab_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['change_type'], name='configurati_change__21fe56_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['changed_at'], name='configurati_changed_ba4197_idx'),
        ),
    ]
