# Generated by Django 4.2.10 on 2025-08-08 11:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('audited_by', models.UUIDField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('total_items_audited', models.IntegerField(default=0)),
                ('discrepancies_found', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_audits',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.JSONField(default=dict)),
                ('contact_info', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(help_text='Maximum capacity', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouses',
                'indexes': [models.Index(fields=['is_active'], name='warehouses_is_acti_178fdd_idx'), models.Index(fields=['code'], name='warehouses_code_339055_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('quantity_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_reserved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_sold', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_stock_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_quantity', models.IntegerField()),
                ('physical_quantity', models.IntegerField()),
                ('discrepancy', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('audited_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryaudit')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_audit_items',
            },
        ),
        migrations.AddField(
            model_name='inventoryaudit',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONFIRMED', 'Confirmed'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('reference_type', models.CharField(default='order', max_length=50)),
                ('reference_id', models.UUIDField(db_index=True)),
                ('reserved_by', models.UUIDField(db_index=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'stock_reservations',
                'indexes': [models.Index(fields=['status'], name='stock_reser_status_be06ad_idx'), models.Index(fields=['reference_type', 'reference_id'], name='stock_reser_referen_49ae4d_idx'), models.Index(fields=['expires_at'], name='stock_reser_expires_fdd22d_idx'), models.Index(fields=['reserved_by'], name='stock_reser_reserve_39435c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired')], max_length=20)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'stock_movements',
                'indexes': [models.Index(fields=['movement_type'], name='stock_movem_movemen_d922c9_idx'), models.Index(fields=['reference_type', 'reference_id'], name='stock_movem_referen_a0d8b9_idx'), models.Index(fields=['created_at'], name='stock_movem_created_07bdcc_idx'), models.Index(fields=['performed_by'], name='stock_movem_perform_b5b0fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('OVERSTOCK', 'Overstock'), ('EXPIRED_RESERVATION', 'Expired Reservation')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('message', models.TextField()),
                ('current_quantity', models.IntegerField()),
                ('threshold_quantity', models.IntegerField(blank=True, null=True)),
                ('acknowledged_by', models.UUIDField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'stock_alerts',
                'indexes': [models.Index(fields=['alert_type'], name='stock_alert_alert_t_206d4a_idx'), models.Index(fields=['status'], name='stock_alert_status_2cc1a6_idx'), models.Index(fields=['created_at'], name='stock_alert_created_9f8b1b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product_id'], name='inventory_i_product_33f9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='inventory_i_sku_af71e8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['quantity_available'], name='inventory_i_quantit_002dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['reorder_level'], name='inventory_i_reorder_c0496b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('product_id', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryaudititem',
            unique_together={('audit', 'inventory_item')},
        ),
        migrations.AddIndex(
            model_name='inventoryaudit',
            index=models.Index(fields=['audit_date'], name='inventory_a_audit_d_0981de_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryaudit',
            index=models.Index(fields=['status'], name='inventory_a_status_8ec8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryaudit',
            index=models.Index(fields=['audited_by'], name='inventory_a_audited_40fd9e_idx'),
        ),
    ]
