name: Security Scan
on: [push, pull_request]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scan Docker Images
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "products-service:latest"
        format: "table"
        exit-code: "1"
        severity: "CRITICAL,HIGH"
